# Generated by Django 5.1.1 on 2024-09-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(help_text='Введите фото', upload_to='uploads/images', verbose_name='Фото товара')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('client', models.CharField(max_length=100, verbose_name='Клиент')),
                ('name', models.CharField(help_text='Введите товар', max_length=100, verbose_name='Товар')),
                ('category', models.CharField(blank=True, choices=[('Процессоры', 'Процессоры'), ('Материнские платы', 'Материнские платы'), ('Видеокарты', 'Видеокарты'), ('Оперативная память', 'Оперативная память'), ('SSD-диски', 'SSD-диски'), ('HDD-диски', 'HDD-диски'), ('Блоки питания>', 'Блоки питания')], max_length=50, null=True, verbose_name='Категория')),
                ('date_created', models.DateField(verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('Поступил', 'Поступил'), ('Выполняется', 'Выполняется'), ('Закрыт', 'Закрыт')], max_length=50, verbose_name='Статус')),
                ('completed', models.BooleanField(default=False, verbose_name='Заказ завершен')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
